---
- name: Testing using the chocolatey module
  hosts: windows

  tasks:
   - name: Running the ipconfig command
     raw: ipconfig
     register: ipconfig

   - debug:
       var: ipconfig

   - name: Use Chocolatey to install git
     win_chocolatey: 
       name: git

   - name: Use Chocolatey to install notepad++
     win_chocolatey: 
       name: notepadplusplus.install
# This playbook installs and enables IIS on Windows hosts
   - name: Install IIS
     win_feature:
       name: "Web-Server"
       state: present
       restart: yes
       include_sub_features: yes
       include_management_tools: yes
